#!/usr/bin/env python3
"""
DOI-URL CSV Importer for PostgreSQL
===================================

This script imports the CSV file generated by the OpenAlex URL extractor
into PostgreSQL tables for efficient DOI-URL mapping.

Features:
- Efficient batch processing with configurable batch sizes
- Data validation and cleaning
- Duplicate handling with upsert capability
- Progress tracking and logging
- Resume functionality for interrupted imports
- URL quality scoring based on source characteristics

Usage:
    python import_doi_urls.py --csv-file doi_urls.csv --db-name biomedical 
                              --db-user myuser --db-password mypass
"""

import argparse
import csv
import logging
import sys
import time
from pathlib import Path
from typing import Dict, List, Any, Optional, Tuple
from urllib.parse import urlparse
import re

try:
    import psycopg2
    from psycopg2 import sql
    from psycopg2.extras import execute_values, RealDictCursor
except ImportError:
    print("Error: psycopg2 not found. Install with: pip install psycopg2-binary")
    sys.exit(1)

# Set up logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(levelname)s - %(message)s',
    handlers=[
        logging.FileHandler('doi_url_import.log'),
        logging.StreamHandler()
    ]
)
logger = logging.getLogger(__name__)

class DOIURLImporter:
    def __init__(self, db_config: Dict[str, str], csv_file: str, 
                 batch_size: int = 10000, create_tables: bool = True):
        self.db_config = db_config
        self.csv_file = Path(csv_file)
        self.batch_size = batch_size
        self.create_tables = create_tables
        
        # Statistics
        self.stats = {
            'total_rows_processed': 0,
            'rows_inserted': 0,
            'rows_updated': 0,
            'rows_skipped': 0,
            'duplicate_dois': 0,
            'invalid_urls': 0,
            'start_time': None,
            'end_time': None
        }

    def connect_db(self):
        """Establish database connection"""
        try:
            conn = psycopg2.connect(**self.db_config)
            return conn
        except psycopg2.Error as e:
            logger.error(f"Database connection failed: {e}")
            raise

    def create_schema(self):
        """Create the DOI-URL mapping tables"""
        logger.info("Creating DOI-URL schema...")
        
        schema_sql = """
        -- Main table for DOI to URL mappings
        CREATE TABLE IF NOT EXISTS doi_urls (
            id BIGSERIAL PRIMARY KEY,
            doi TEXT NOT NULL,
            url TEXT NOT NULL,
            openalex_id TEXT,
            title TEXT,
            publication_year INTEGER,
            location_type TEXT NOT NULL,
            version TEXT,
            license TEXT,
            host_type TEXT,
            oa_status TEXT,
            is_oa BOOLEAN DEFAULT FALSE,
            url_quality_score INTEGER DEFAULT 50,
            last_verified TIMESTAMP,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        );

        -- Indexes for efficient querying
        CREATE INDEX IF NOT EXISTS idx_doi_urls_doi ON doi_urls(doi);
        CREATE INDEX IF NOT EXISTS idx_doi_urls_url ON doi_urls(url);
        CREATE INDEX IF NOT EXISTS idx_doi_urls_doi_location_type ON doi_urls(doi, location_type);
        CREATE INDEX IF NOT EXISTS idx_doi_urls_oa_status ON doi_urls(oa_status) WHERE is_oa = TRUE;
        CREATE INDEX IF NOT EXISTS idx_doi_urls_host_type ON doi_urls(host_type);
        CREATE INDEX IF NOT EXISTS idx_doi_urls_publication_year ON doi_urls(publication_year);

        -- Unique constraint to prevent duplicate DOI-URL pairs
        DO $$ 
        BEGIN
            BEGIN
                ALTER TABLE doi_urls ADD CONSTRAINT unique_doi_url UNIQUE(doi, url);
            EXCEPTION
                WHEN duplicate_table THEN
                    -- Constraint already exists
                    NULL;
            END;
        END $$;

        -- Optional metadata table
        CREATE TABLE IF NOT EXISTS doi_metadata (
            doi TEXT PRIMARY KEY,
            openalex_id TEXT UNIQUE,
            title TEXT,
            publication_year INTEGER,
            work_type TEXT,
            is_retracted BOOLEAN DEFAULT FALSE,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        );

        CREATE INDEX IF NOT EXISTS idx_doi_metadata_year ON doi_metadata(publication_year);
        CREATE INDEX IF NOT EXISTS idx_doi_metadata_type ON doi_metadata(work_type);
        """
        
        with self.connect_db() as conn:
            with conn.cursor() as cur:
                try:
                    cur.execute(schema_sql)
                    conn.commit()
                    logger.info("Schema created successfully")
                except psycopg2.Error as e:
                    logger.error(f"Schema creation failed: {e}")
                    raise

    def validate_and_clean_row(self, row: Dict[str, str]) -> Optional[Dict[str, Any]]:
        """Validate and clean a single CSV row"""
        
        # Required fields
        doi = row.get('doi', '').strip()
        url = row.get('url', '').strip()
        location_type = row.get('location_type', '').strip()
        
        if not doi or not url or not location_type:
            return None
        
        # Validate DOI format
        if not self._is_valid_doi(doi):
            logger.warning(f"Invalid DOI format: {doi}")
            return None
        
        # Validate URL
        if not self._is_valid_url(url):
            self.stats['invalid_urls'] += 1
            logger.warning(f"Invalid URL: {url}")
            return None
        
        # Clean and convert data
        # Extract DOI identifier for the DOI field, but keep URL as-is
        clean_doi = self._extract_doi_from_url(doi).lower()

        cleaned_row = {
            'doi': clean_doi,  # Store only DOI identifier
            'url': url,  # Keep full URL as-is
            'openalex_id': row.get('openalex_id', '').strip() or None,
            'title': row.get('title', '').strip() or None,
            'publication_year': self._safe_int(row.get('publication_year')),
            'location_type': location_type.lower(),
            'version': row.get('version', '').strip() or None,
            'license': row.get('license', '').strip() or None,
            'host_type': row.get('host_type', '').strip() or None,
            'oa_status': row.get('oa_status', '').strip() or None,
            'is_oa': self._safe_bool(row.get('is_oa')),
            'url_quality_score': self._calculate_url_quality_score(row)
        }
        
        return cleaned_row

    def _extract_doi_from_url(self, doi_input: str) -> str:
        """Extract DOI identifier from DOI URL or return as-is if already a DOI"""
        doi_input = doi_input.strip()

        # If it's a DOI URL, extract the DOI part
        if doi_input.startswith('https://doi.org/') or doi_input.startswith('http://doi.org/'):
            return doi_input.split('doi.org/')[-1]
        elif doi_input.startswith('doi:'):
            return doi_input[4:]  # Remove 'doi:' prefix
        else:
            return doi_input

    def _is_valid_doi(self, doi: str) -> bool:
        """Validate DOI format"""
        # Extract DOI identifier if it's a URL
        clean_doi = self._extract_doi_from_url(doi)

        # Basic DOI regex pattern - DOI should start with 10.
        doi_pattern = r'^10\.\d{4,}/[^\s]+$'
        return bool(re.match(doi_pattern, clean_doi, re.IGNORECASE))

    def _is_valid_url(self, url: str) -> bool:
        """Validate URL format"""
        try:
            parsed = urlparse(url)
            return bool(parsed.scheme and parsed.netloc)
        except:
            return False

    def _safe_int(self, value: str) -> Optional[int]:
        """Safely convert string to integer"""
        if not value or value.strip() == '':
            return None
        try:
            return int(value.strip())
        except (ValueError, TypeError):
            return None

    def _safe_bool(self, value: str) -> bool:
        """Safely convert string to boolean"""
        if not value:
            return False
        value_lower = value.strip().lower()
        return value_lower in ('true', '1', 'yes', 't')

    def _calculate_url_quality_score(self, row: Dict[str, str]) -> int:
        """Calculate quality score for URL based on various factors"""
        score = 50  # Base score
        
        # Location type scoring
        location_type = row.get('location_type', '').lower()
        if location_type == 'primary':
            score += 20
        elif location_type == 'best_oa':
            score += 15
        elif location_type == 'alternate':
            score += 5
        
        # Open access scoring
        if self._safe_bool(row.get('is_oa')):
            score += 10
            
            oa_status = row.get('oa_status', '').lower()
            if oa_status == 'gold':
                score += 10
            elif oa_status == 'green':
                score += 5
        
        # Version scoring
        version = row.get('version', '').lower()
        if 'published' in version:
            score += 10
        elif 'accepted' in version:
            score += 5
        
        # Host type scoring
        host_type = row.get('host_type', '').lower()
        if host_type in ['journal', 'doaj_journal']:
            score += 10
        elif host_type == 'repository':
            score += 8
        elif host_type == 'preprint_server':
            score += 5
        
        # Domain reputation (simple heuristic)
        url = row.get('url', '').lower()
        reputable_domains = [
            'pubmed', 'pmc', 'doi.org', 'nature.com', 'science.org',
            'elsevier.com', 'springer.com', 'wiley.com', 'arxiv.org',
            'biorxiv.org', 'medrxiv.org'
        ]
        if any(domain in url for domain in reputable_domains):
            score += 5
        
        return min(100, max(0, score))  # Clamp between 0-100

    def read_csv_in_batches(self) -> List[List[Dict[str, Any]]]:
        """Read CSV file and yield batches of validated rows"""
        if not self.csv_file.exists():
            raise FileNotFoundError(f"CSV file not found: {self.csv_file}")
        
        logger.info(f"Reading CSV file: {self.csv_file}")
        
        batches = []
        current_batch = []
        
        with open(self.csv_file, 'r', encoding='utf-8') as csvfile:
            # Detect delimiter with fallback
            sample = csvfile.read(1024)
            csvfile.seek(0)

            delimiter = ','  # Default fallback
            try:
                sniffer = csv.Sniffer()
                detected_delimiter = sniffer.sniff(sample).delimiter
                delimiter = detected_delimiter
                logger.info(f"Detected CSV delimiter: '{delimiter}'")
            except csv.Error as e:
                logger.warning(f"Could not detect delimiter ({e}), using comma as fallback")

            reader = csv.DictReader(csvfile, delimiter=delimiter)
            
            for row_num, row in enumerate(reader, 1):
                cleaned_row = self.validate_and_clean_row(row)
                
                if cleaned_row:
                    current_batch.append(cleaned_row)
                else:
                    self.stats['rows_skipped'] += 1
                
                self.stats['total_rows_processed'] += 1
                
                # When batch is full, add to batches list
                if len(current_batch) >= self.batch_size:
                    batches.append(current_batch)
                    current_batch = []
                
                # Progress logging
                if row_num % 50000 == 0:
                    logger.info(f"Processed {row_num} rows from CSV")
            
            # Add final batch if not empty
            if current_batch:
                batches.append(current_batch)
        
        logger.info(f"CSV processing complete. {len(batches)} batches prepared.")
        return batches

    def insert_batch(self, batch: List[Dict[str, Any]], connection) -> Tuple[int, int]:
        """Insert a batch of rows using efficient bulk insert with conflict resolution"""
        
        if not batch:
            return 0, 0
        
        # Prepare data for bulk insert
        insert_data = []
        for row in batch:
            insert_data.append((
                row['doi'],
                row['url'], 
                row['openalex_id'],
                row['title'],
                row['publication_year'],
                row['location_type'],
                row['version'],
                row['license'],
                row['host_type'],
                row['oa_status'],
                row['is_oa'],
                row['url_quality_score']
            ))
        
        insert_sql = """
        INSERT INTO doi_urls (
            doi, url, openalex_id, title, publication_year, location_type,
            version, license, host_type, oa_status, is_oa, url_quality_score
        ) VALUES %s
        ON CONFLICT (doi, url) DO UPDATE SET
            openalex_id = EXCLUDED.openalex_id,
            title = EXCLUDED.title,
            publication_year = EXCLUDED.publication_year,
            location_type = EXCLUDED.location_type,
            version = EXCLUDED.version,
            license = EXCLUDED.license,
            host_type = EXCLUDED.host_type,
            oa_status = EXCLUDED.oa_status,
            is_oa = EXCLUDED.is_oa,
            url_quality_score = EXCLUDED.url_quality_score,
            updated_at = CURRENT_TIMESTAMP
        """
        
        try:
            with connection.cursor() as cur:
                # Get count before insert
                cur.execute("SELECT COUNT(*) FROM doi_urls")
                count_before = cur.fetchone()[0]
                
                # Execute bulk insert
                execute_values(
                    cur, insert_sql, insert_data,
                    template=None, page_size=self.batch_size
                )
                
                # Get count after insert  
                cur.execute("SELECT COUNT(*) FROM doi_urls")
                count_after = cur.fetchone()[0]
                
                connection.commit()
                
                rows_affected = count_after - count_before
                rows_updated = len(batch) - rows_affected
                
                return rows_affected, rows_updated
                
        except psycopg2.Error as e:
            connection.rollback()
            logger.error(f"Batch insert failed: {e}")
            raise

    def update_doi_metadata(self, connection):
        """Update the separate doi_metadata table with aggregated information"""
        logger.info("Updating DOI metadata table...")
        
        metadata_sql = """
        INSERT INTO doi_metadata (doi, openalex_id, title, publication_year)
        SELECT DISTINCT 
            doi,
            openalex_id,
            title,
            publication_year
        FROM doi_urls
        WHERE doi IS NOT NULL
        ON CONFLICT (doi) DO UPDATE SET
            openalex_id = EXCLUDED.openalex_id,
            title = EXCLUDED.title,
            publication_year = EXCLUDED.publication_year,
            updated_at = CURRENT_TIMESTAMP;
        """
        
        try:
            with connection.cursor() as cur:
                cur.execute(metadata_sql)
                rows_affected = cur.rowcount
                connection.commit()
                logger.info(f"Updated {rows_affected} DOI metadata records")
        except psycopg2.Error as e:
            connection.rollback()
            logger.error(f"DOI metadata update failed: {e}")

    def print_final_stats(self):
        """Print import statistics"""
        duration = (self.stats['end_time'] - self.stats['start_time']).total_seconds()
        
        logger.info("=" * 60)
        logger.info("DOI-URL IMPORT COMPLETED")
        logger.info("=" * 60)
        logger.info(f"Total rows processed: {self.stats['total_rows_processed']:,}")
        logger.info(f"Rows inserted: {self.stats['rows_inserted']:,}")
        logger.info(f"Rows updated: {self.stats['rows_updated']:,}")
        logger.info(f"Rows skipped (invalid): {self.stats['rows_skipped']:,}")
        logger.info(f"Invalid URLs filtered: {self.stats['invalid_urls']:,}")
        logger.info(f"Import duration: {duration:.1f} seconds")
        logger.info(f"Processing rate: {self.stats['total_rows_processed']/duration:.1f} rows/sec")

    def run_import(self):
        """Execute the complete import process"""
        logger.info("Starting DOI-URL import process...")
        self.stats['start_time'] = time.time()
        
        try:
            # Create schema if requested
            if self.create_tables:
                self.create_schema()
            
            # Read and process CSV in batches
            batches = self.read_csv_in_batches()
            
            # Import batches
            with self.connect_db() as conn:
                for i, batch in enumerate(batches, 1):
                    logger.info(f"Processing batch {i}/{len(batches)} ({len(batch)} rows)")
                    
                    rows_inserted, rows_updated = self.insert_batch(batch, conn)
                    self.stats['rows_inserted'] += rows_inserted
                    self.stats['rows_updated'] += rows_updated
                    
                    logger.info(f"Batch {i}: {rows_inserted} inserted, {rows_updated} updated")
                
                # Update metadata table
                self.update_doi_metadata(conn)
            
            self.stats['end_time'] = time.time()
            self.print_final_stats()
            
        except Exception as e:
            logger.error(f"Import failed: {e}")
            raise


def main():
    parser = argparse.ArgumentParser(description='Import DOI-URL CSV into PostgreSQL')
    parser.add_argument('--csv-file', required=True,
                        help='Path to CSV file with DOI-URL mappings')
    parser.add_argument('--db-host', default='localhost',
                        help='PostgreSQL host')
    parser.add_argument('--db-port', type=int, default=5432,
                        help='PostgreSQL port')
    parser.add_argument('--db-name', required=True,
                        help='PostgreSQL database name')
    parser.add_argument('--db-user', required=True,
                        help='PostgreSQL username')
    parser.add_argument('--db-password', required=True,
                        help='PostgreSQL password')
    parser.add_argument('--batch-size', type=int, default=10000,
                        help='Batch size for bulk inserts (default: 10000)')
    parser.add_argument('--skip-create-tables', action='store_true',
                        help='Skip table creation (tables already exist)')
    
    args = parser.parse_args()
    
    # Database configuration
    db_config = {
        'host': args.db_host,
        'port': args.db_port,
        'database': args.db_name,
        'user': args.db_user,
        'password': args.db_password
    }
    
    # Create importer and run
    importer = DOIURLImporter(
        db_config=db_config,
        csv_file=args.csv_file,
        batch_size=args.batch_size,
        create_tables=not args.skip_create_tables
    )
    
    importer.run_import()


if __name__ == '__main__':
    main()
